name: 'Build Sign Scan'
description: 'Builds a docker image, signs, snyk scans, and pushes to algol60'
inputs:
  docker_repo:
    description: Full path of repo to push eg csm-docker/stable/curl
    required: true

  docker_tag:
    description: Tag to use when pushing
    required: true

  context_path:
    description: Path to folder containing dockerfile to build
    required: true

  # Defaults
  docker_registry:
    description: Name of registry to push to
    required: true
    default: 'artifactory.algol60.net'

  docker_registry_user:
    description: User for authing with registry
    required: true
    default: 'github-actions-cray-hpe'

  docker_registry_password:
    description: Password to auth with registry
    required: true
    default: ${{ secrets.ARTIFACTORY_ALGOL60_TOKEN }}



runs:
  using: "composite"

  steps:
    - name: Install cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v1.0.0'

    - name: Check cosign install
      run: cosign version

    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: artifactory.algol60.net
        username: ${{ inputs.docker_registry_user }}
        password: ${{ inputs.docker_registry_password }}

    - name: Set up Cloud SDK for Signing
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.COSIGN_GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.COSIGN_GCP_SA_KEY }}
        export_default_credentials: true

    - name: Use gcloud CLI
      run: gcloud info

    - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context_path }}
          push: true
          tags: |
            ${{ inputs.docker_registry }}/${{ inputs.docker_repo }}:${{ inputs.docker_tag }}

    - name: Sign
      env:
        COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
      run: |
        cosign sign -key $COSIGN_KEY -a GIT_HASH=$GITHUB_SHA ${{ inputs.docker_registry }}/${{ inputs.docker_repo }}:${{ inputs.docker_tag }}

    - name: Snyk Scan
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ inputs.docker_registry }}/${{ inputs.docker_repo }}:${{ inputs.docker_tag }}
