FROM quay.io/cephcsi/cephcsi:v2.1.2
RUN yum -y update && yum clean all
RUN yum -y update http://ftp.scientificlinux.org/linux/scientific/7/x86_64/updates/security/pyldb-1.5.4-2.el7_9.x86_64.rpm \
     http://ftp.scientificlinux.org/linux/scientific/7/x86_64/updates/security/pyldb-devel-1.5.4-2.el7_9.x86_64.rpm \
     http://ftp.scientificlinux.org/linux/scientific/7/x86_64/updates/security/libldb-1.5.4-2.el7_9.x86_64.rpm \
     http://ftp.scientificlinux.org/linux/scientific/7/x86_64/updates/security/libldb-devel-1.5.4-2.el7_9.x86_64.rpm


