name: Status Update

on:
  workflow_dispatch: {}

  schedule:
    # Update schedule every night
    - cron: "0 8 * * *"

jobs:
  scan:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: snyk/actions/setup@master

      - name: Setup trivy
        shell: bash
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.tar.gz
          tar xvf trivy_0.19.2_Linux-64bit.tar.gz trivy
          sudo mv trivy /usr/local/bin

      - name: Scan Images
        run: .github/scripts/scan_all_images.sh
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Github actions status update
          file_pattern: status.md
