name: Status Update

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: snyk/actions/setup@master

      - name: Scan Images
        run: .github/scripts/scan_all_images.sh
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      - name: Commit status
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions-runner@hpe.com'
          git add status.md
          (git commit -m "Status Update" && git push) || echo "No changes"
