name: quay.io/coreos/prometheus-operator:v0.38.1

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/quay.io.coreos.prometheus-operator.v0.38.1.yaml
      - quay.io/coreos/prometheus-operator/v0.38.1/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/quay.io.coreos.prometheus-operator.v0.38.1.yaml
      - quay.io/coreos/prometheus-operator/v0.38.1/**
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      CONTEXT_PATH: quay.io/coreos/prometheus-operator/v0.38.1
      DOCKER_REPO: artifactory.algol60.net/csm-docker/stable/quay.io/coreos/prometheus-operator
      DOCKER_TAG: v0.38.1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.0.0'

      - name: Check cosign install
        run: cosign version

      - name: Login to algol60 Container Registry
        uses: docker/login-action@v1
        with:
          registry: artifactory.algol60.net
          username: github-actions-cray-hpe
          password: ${{ secrets.ARTIFACTORY_ALGOL60_TOKEN }}

      - name: Set up Cloud SDK for Signing
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.COSIGN_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.COSIGN_GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info

      - name: Build Only
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.CONTEXT_PATH }}
          push: false
          tags: |
            ${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}

      - name: Build and Push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.CONTEXT_PATH }}
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}

      - name: Sign
        if: github.ref == 'refs/heads/main'
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
        run: |
          cosign sign -key $COSIGN_KEY -a GIT_HASH=$GITHUB_SHA ${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}

      - name: Snyk Scan
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
